<?php
session_start();

// Ensure the user is an admin and logged in
if (!isset($_SESSION['is_admin']) || $_SESSION['is_admin'] != 1) {
    header("Location: index.php");
    exit;
}

// Database connection
$conn = new mysqli("localhost", "root", "", "cafe_pos");
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

function safeNumberFormat($number, $decimals = 2) {
    return number_format(floatval($number ?? 0), $decimals);
}

// Set default timezone to Philippines
date_default_timezone_set('Asia/Manila');

// Get filter parameters
$timeFilter = isset($_GET['time_filter']) ? $_GET['time_filter'] : 'day';
$startDate = isset($_GET['start_date']) ? $_GET['start_date'] : date('Y-m-d');
$endDate = isset($_GET['end_date']) ? $_GET['end_date'] : date('Y-m-d');

// Get current date in Philippines timezone
$currentDate = new DateTime('now', new DateTimeZone('Asia/Manila'));

// Prepare date condition based on filter
switch($timeFilter) {
    case 'day':
        $dateCondition = "1=1";
        $displayDateRange = "Daily Sales Report (All Time)";
        $groupBy = "DATE(t.transaction_date)";
        break;
    case 'month':
        $currentYear = $currentDate->format('Y');
        $dateCondition = "YEAR(t.transaction_date) = '$currentYear'";
        $displayDateRange = "Monthly Sales Report - " . $currentDate->format('Y');
        $groupBy = "MONTH(t.transaction_date)";
        break;
    case 'year':
        $dateCondition = "1=1";
        $displayDateRange = "Annual Sales Report";
        $groupBy = "YEAR(t.transaction_date)";
        break;
    case 'custom':
        $startDateTime = new DateTime($startDate);
        $endDateTime = new DateTime($endDate);
        $dateCondition = "DATE(t.transaction_date) BETWEEN '" . $startDateTime->format('Y-m-d') . "' AND '" . $endDateTime->format('Y-m-d') . "'";
        $displayDateRange = "Sales Report: " . $startDateTime->format('F d, Y') . " to " . $endDateTime->format('F d, Y');
        $groupBy = "DATE(t.transaction_date)";
        break;
    default:
        $dateCondition = "DATE(t.transaction_date) = '" . $currentDate->format('Y-m-d') . "'";
        $displayDateRange = "Daily Sales Report - " . $currentDate->format('F d, Y');
        $groupBy = "DATE(t.transaction_date)";
}

// Query for sales data
$salesTableQuery = "
    SELECT 
        CASE 
            WHEN '$timeFilter' = 'year' THEN YEAR(t.transaction_date)
            WHEN '$timeFilter' = 'month' THEN DATE_FORMAT(t.transaction_date, '%Y-%m')
            ELSE DATE(t.transaction_date)
        END as date_group,
        COUNT(*) as transaction_count,
        SUM(t.total_amount) as total_sales,
        SUM(CASE WHEN t.payment_code = 'CASH' THEN t.total_amount ELSE 0 END) as cash_sales,
        SUM(CASE WHEN t.payment_code = 'GCASH' THEN t.total_amount ELSE 0 END) as gcash_sales,
        SUM(CASE WHEN t.payment_code = 'MAYA' THEN t.total_amount ELSE 0 END) as maya_sales
    FROM transactions t
    WHERE $dateCondition
    GROUP BY date_group
    ORDER BY date_group DESC";

$salesTableResult = $conn->query($salesTableQuery);
$tableData = [];
$grandTotal = 0;
$grandTransactions = 0;
$grandCash = 0;
$grandGcash = 0;
$grandMaya = 0;

while ($row = $salesTableResult->fetch_assoc()) {
    $tableData[] = $row;
    $grandTotal += $row['total_sales'];
    $grandTransactions += $row['transaction_count'];
    $grandCash += $row['cash_sales'];
    $grandGcash += $row['gcash_sales'];
    $grandMaya += $row['maya_sales'];
}

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="Sales_Report_' . date('Y-m-d_H-i') . '.csv"');
header('Pragma: no-cache');
header('Expires: 0');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for UTF-8
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// ===== FORMAL REPORT HEADER =====
fputcsv($output, ['CAFÉ POS SYSTEM - OFFICIAL SALES REPORT']);
fputcsv($output, ['']);

// Report details with proper spacing
$reportDetails = [
    ['Report Period:', $displayDateRange],
    ['Generated:', date('F d, Y \a\t h:i A')],
    ['Generated By:', 'Administrative User'],
    ['', ''],
    ['SUMMARY OVERVIEW', ''],
    ['Total Periods Reported:', count($tableData)],
    ['Total Transactions:', $grandTransactions],
    ['Total Sales Revenue:', '₱ ' . safeNumberFormat($grandTotal)],
    ['', ''],
    ['Payment Method Breakdown:', ''],
    ['Cash Payments:', '₱ ' . safeNumberFormat($grandCash)],
    ['GCash Payments:', '₱ ' . safeNumberFormat($grandGcash)],
    ['Maya Payments:', '₱ ' . safeNumberFormat($grandMaya)],
    ['', ''],
    ['', ''],
    ['DETAILED SALES BREAKDOWN', ''],
    ['', '']
];

foreach ($reportDetails as $detail) {
    fputcsv($output, $detail);
}

// ===== DETAILED TRANSACTION DATA =====
// Table headers with padded spacing
fputcsv($output, [
    'DATE',
    'TRANSACTIONS',
    'CASH SALES',
    'GCASH SALES', 
    'MAYA SALES',
    'TOTAL SALES'
]);

// Data rows with proper formatting
foreach($tableData as $row) {
    $dateDisplay = '';
    switch($timeFilter) {
        case 'year':
            $dateDisplay = $row['date_group'];
            break;
        case 'month':
            $date = DateTime::createFromFormat('Y-m', $row['date_group']);
            $dateDisplay = $date->format('F Y');
            break;
        default:
            $date = new DateTime($row['date_group']);
            $dateDisplay = $date->format('M d, Y');
    }
    
    fputcsv($output, [
        $dateDisplay,
        $row['transaction_count'],
        '₱' . safeNumberFormat($row['cash_sales']),
        '₱' . safeNumberFormat($row['gcash_sales']),
        '₱' . safeNumberFormat($row['maya_sales']),
        '₱' . safeNumberFormat($row['total_sales'])
    ]);
}

fputcsv($output, ['']);
fputcsv($output, ['']);

// ===== GRAND TOTALS SECTION =====
fputcsv($output, ['GRAND TOTALS', '', '', '', '', '']);
fputcsv($output, [
    'TOTAL',
    $grandTransactions,
    '₱' . safeNumberFormat($grandCash),
    '₱' . safeNumberFormat($grandGcash),
    '₱' . safeNumberFormat($grandMaya),
    '₱' . safeNumberFormat($grandTotal)
]);

// ===== REPORT FOOTER =====
fputcsv($output, ['']);
fputcsv($output, ['']);
fputcsv($output, ['END OF REPORT']);
fputcsv($output, ['Confidential Business Document - For Internal Use Only']);
fputcsv($output, ['Café POS System - ' . date('Y')]);

// Close connection and output stream
fclose($output);
$conn->close();
exit;
?>